#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/downloads

# copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json

[[ ! -f /config/remove_finished_ratio2.sh ]] && cp \
	/defaults/remove_finished_ratio2.sh /config/remove_finished_ratio2.sh

# copy blocklist-update script
[[ ! -f /config/blocklist-update.sh ]] && cp \
	/defaults/blocklist-update.sh /config/blocklist-update.sh

# permissions
chown -R abc:abc \
	/config \
	/downloads

chmod 755 /config/blocklist-update.sh
