FROM goofball222/unifi:latest

# set version label
ARG BUILD_DATE=20190102
ARG VERSION=5.9.29
LABEL build_version="version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="s.isaenkov"
LABEL description="UniFi Controller"
